"""
psck_mmd.shallow_deploy — Shallow / constant-depth deployment of a trained
MoIQP at constant depth, replacing the depth-catastrophic naive cIQP.

═════════════════════════════════════════════════════════════════════════════
WHY THE NAIVE cIQP IS UNDEPLOYABLE (first principles)
═════════════════════════════════════════════════════════════════════════════
Global-depolarizing fidelity is a GATE-COUNT functional, F ≈ exp(-p2q·N2q);
depth only adds idle decoherence. The naive cIQP has three independent
killers:
  (K1) count:      |G|·2^a compiled gates, weight up to 2+a (CX ladders);
  (K2) congestion: every S≠∅ gate passes through one of only a physical
                   ancilla qubits → depth Ω(|G|·L/a) irrespective of data
                   parallelism;
  (K3) routing:    data↔ancilla and non-native data edges need SWAP chains.
Furthermore, any EXACT COHERENT implementation must physically encode every
nonzero Walsh coefficient φ̃_{j,S} as some gate angle: coherent gate count is
Ω(nnz(φ̃)). Arbitrary-angle diagonals sit outside the Clifford hierarchy, so
gate teleportation cannot compress them (the correction D Z_x D† is another
arbitrary diagonal). The only legitimate levers are therefore:
  (L1) remove the coherent ancillas          →  dcIQP  (this module, §1)
  (L2) shrink nnz(φ̃) at TRAINING time       →  Walsh-sparse MoIQP (§3)
  (L3) de-congest ancillas via GHZ fan-out   →  cat-cIQP (§2)

═════════════════════════════════════════════════════════════════════════════
§1  dcIQP — dynamic-circuit cIQP (EXACT, constant depth, count = 1 component)
═════════════════════════════════════════════════════════════════════════════
The cIQP diagonal commutes with Z-basis measurement of the ancilla register
(it is diagonal on the ancillas). Un-deferring the deferred measurement:

    H^{⊗a} on ancillas → measure ancillas → ℓ ~ Uniform(2^a)
    → feedforward: apply the SINGLE-component circuit U(θ^{(ℓ)}) on data.

The data-register distribution is EXACTLY p_MoIQP (paper Eq. (A15) read
right-to-left; deferred-measurement principle). Ordering matters:
the ancilla measurement + classical feedforward happen while the data qubits
are still in |0⟩, which is an eigenstate of both dephasing and amplitude
damping's fixed point — the feedforward latency is therefore (almost) free.
Cost: dynamic circuits on some platforms exclude fractional rzz, so each
ZZ term costs 2 CZ instead of 1 native rzz.

The classical-per-shot mixture (sample ℓ classically, bind parameters, keep
fractional rzz) is distributionally identical and strictly cheaper; dcIQP's
only additional value is that the mixture index is generated by on-chip
quantum randomness inside one self-contained circuit.

═════════════════════════════════════════════════════════════════════════════
§2  cat-cIQP — coherent constant-depth-in-n via GHZ ancilla buses
═════════════════════════════════════════════════════════════════════════════
Replace each logical ancilla k by an m-qubit GHZ "bus"
    |cat_k⟩ = (|0⟩^{⊗m} + |1⟩^{⊗m})/√2 .
Z on ANY single copy acts as the logical Z̄_k (Z_i|0..0⟩=+|0..0⟩,
Z_i|1..1⟩=−|1..1⟩ for every i). The joint ancilla state
⊗_k |cat_k⟩ = (1/√L) Σ_ℓ |enc(ℓ)⟩ with enc the m-fold repetition encoding,
so every compiled gate exp(i φ̃_{j,S} Z_{G_j} ⊗ Z̄_S) may address the
NEAREST copy of each ancilla in S. This removes killer (K2): with m ~
(parallel gates per layer) copies, all data-disjoint gates run
simultaneously and total depth is O(2^a · a) — constant in n. GHZ buses are
preparable in constant depth with mid-circuit measurement + feedforward
(Bäumer et al., PRX Quantum 5, 030339 (2024)) or depth O(log m) unitarily.
Killer (K1) — gate count — is NOT removed: cat-cIQP remains Ω(nnz(φ̃))
gates. Use it only together with §3. Exactness of the data marginal is
audited to machine precision by dense simulation in audit_shallow_deploy.py.

═════════════════════════════════════════════════════════════════════════════
§3  Walsh-sparse MoIQP — deployment-aware training (original contribution)
═════════════════════════════════════════════════════════════════════════════
Reparameterize the per-component angles in the Walsh domain,
    θ_j^{(ℓ)} = Σ_{S ∈ U} (−1)^{ℓ·S} φ̃_{j,S} ,     U ⊆ 2^{{0..a-1}}, ∅ ∈ U,
and TRAIN φ̃ directly, with a hard support constraint |U| = k ≪ 2^a.
Training cost is unchanged (Van den Nest forward/backward per component;
chain rule dL/dφ̃_{j,S} = Σ_ℓ (−1)^{ℓ·S} dL/dθ_j^{(ℓ)} is one Walsh
synthesis per step). The coherent compiled circuit then has k·|G| gates of
weight ≤ 2 + max_{S∈U}|S| — the information-theoretic optimum is attacked
where it lives, at the encoding size, and the optimizer spends the coherent
budget where the PSCK loss cares. k interpolates between L=1 (U={∅}) and the
full mixture (U = all subsets).

All constructions are exact; nothing in this module is a heuristic
approximation of the trained distribution.
"""
from __future__ import annotations
from dataclasses import dataclass, field
import numpy as np

from .correlator import (
    ParityCache, sample_latents, forward_batch, backward_batch, z_data_batch,
)
from .graph import precompute_active_lists
from .corr_jacobian import pearson_value_and_jacobian
from .psck_kernel import (
    build_psck_kernel, psck_mmd2_and_grad, psck_mmd2_unbiased,
    psck_mmd2_unbiased_grad_wrt_za, heat_kernel_coeffs, psck_diagnostics,
)
from .ciqp import _pad_to_power_of_2, _walsh_hadamard


# ═════════════════════════════════════════════════════════════════════════
# Shared: greedy edge/hypergraph coloring → parallel layers
# ═════════════════════════════════════════════════════════════════════════

def greedy_gate_layers(gates: list[tuple[int, ...]]) -> list[list[int]]:
    """Partition gate indices into layers of pairwise-disjoint support
    (greedy first-fit coloring of the gate-intersection graph). For a
    hardware-native heavy-hex pair layer this returns ≤ 4 layers
    (χ'(heavy-hex)=3 plus the single-qubit layer merged where possible)."""
    layers: list[list[int]] = []
    layer_support: list[set[int]] = []
    order = sorted(range(len(gates)), key=lambda j: -len(gates[j]))
    for j in order:
        gj = set(gates[j])
        placed = False
        for li, sup in enumerate(layer_support):
            if not (sup & gj):
                layers[li].append(j)
                sup |= gj
                placed = True
                break
        if not placed:
            layers.append([j])
            layer_support.append(set(gj))
    return layers


# ═════════════════════════════════════════════════════════════════════════
# Shared: resource / fidelity budget under a global-depolarizing model
# ═════════════════════════════════════════════════════════════════════════

@dataclass
class NoiseModelParams:
    """Generic cost parameters for the depth-versus-width estimate of Sec. VII.

    These are order-of-magnitude figures for a superconducting architecture of
    the 2025/26 era, not measurements of any particular processor. Replace them
    with the calibration of whatever platform is being considered before reading
    the resulting fidelities as anything but a scaling argument."""
    p2q: float = 2.8e-3          # median CZ / fractional-rzz error
    p1q: float = 2.5e-4          # median 1q error
    p_meas: float = 1.2e-2       # median readout assignment error
    t2_us: float = 150.0         # median T2
    ff_latency_us: float = 2.0   # feedforward branch-selection latency
    routing_factor_nonnative: float = 3.0  # SWAP inflation for non-native edges


def _gate_2q_cost(weight: int, fractional_rzz: bool) -> int:
    """Two-qubit-gate cost of one weight-w Z-string rotation, all qubits
    adjacent. w=1: RZ (0). w=2: 1 native rzz/ZZ or 2 CZ. w≥3 without a
    native arbitrary-angle ZZ: CX ladder, 2(w-1) CX + RZ. With a native
    ZZ(θ), available as a fractional two-qubit rotation on some platforms and
    as the MS gate on trapped ions, the ladder
    terminates in one ZZ rotation: CX^{w-2} · ZZ(θ) · CX^{w-2} = 2w-3
    two-qubit gates (identity: CX₁₂ Z₂ CX₁₂ = Z₁Z₂)."""
    if weight <= 1:
        return 0
    if weight == 2:
        return 1 if fractional_rzz else 2
    return (2 * weight - 3) if fractional_rzz else 2 * (weight - 1)


def deployment_budget(gates: list[tuple[int, ...]],
                      n_meas: int,
                      noise: NoiseModelParams,
                      fractional_rzz: bool,
                      native_layout: bool = True,
                      idle_us: float = 0.0,
                      idle_qubits: int = 0,
                      label: str = "") -> dict:
    """Count 2q gates, schedule depth by greedy coloring, and estimate the
    global fidelity F = (1-p2q)^{N2q} (1-p1q)^{N1q} (1-pm)^{n_meas}
                        · exp(-idle_us·idle_qubits/T2).
    `native_layout=False` multiplies N2q by the SWAP routing factor. This is
    an ESTIMATE for triage, not a substitute for transpiling against the
    real backend."""
    weights = [len(g) for g in gates]
    n2q = sum(_gate_2q_cost(w, fractional_rzz) for w in weights)
    if not native_layout:
        n2q = int(round(n2q * noise.routing_factor_nonnative))
    n1q = sum(1 for w in weights if w >= 1)  # one RZ per gate (+ H layers, minor)
    layers = greedy_gate_layers(gates)
    f_gates = (1 - noise.p2q) ** n2q * (1 - noise.p1q) ** n1q
    f_idle = float(np.exp(-idle_us * idle_qubits / noise.t2_us))
    # F_circ: pre-measurement state fidelity under the global-depolarizing
    # surrogate — this is the F that a global-depolarizing fit divides out, and
    # the quantity that decides whether SAMPLES carry the trained structure.
    # Readout is a LOCAL bitflip channel, physically distinct: it attenuates
    # ⟨Z_S⟩ by (1-2ε)^{|S|} and is separately mitigatable (TREX/M3); it is
    # reported apart and must not be folded into the depolarizing F.
    f_meas = (1 - noise.p_meas) ** n_meas
    return {
        "label": label, "n_gates": len(gates), "n_2q": n2q, "n_1q": n1q,
        "sched_layers": len(layers),
        "max_weight": max(weights) if weights else 0,
        "F_gates": f_gates, "F_idle": f_idle,
        "F_circ": f_gates * f_idle,
        "F_readout": f_meas,
        "F_total": f_gates * f_meas * f_idle,
    }


# ═════════════════════════════════════════════════════════════════════════
# RZZ angle canonicalization (fractional gates typically accept θ ∈ [0, π/2] only)
# ═════════════════════════════════════════════════════════════════════════

def fold_rzz(theta: float):
    """RZZ(θ) = pre · RZZ(θ_c) · post up to global phase, θ_c ∈ [0, π/2].
    Identities: X₀-conjugation flips the ZZ sign; RZZ(π) = −i Z⊗Z.
    NUMERICALLY VERIFIED to 7e-16 over 4008 angles incl. all branch
    boundaries and −π/2 (an angle some transpilers reject in
    validate_rzz_pubs on unfolded circuits). Returns
    (theta_c, pre_ops, post_ops) with ops ∈ {("x",0),("z",0),("z",1)},
    to be emitted immediately around the rzz on (q0, q1)."""
    import math
    t = float(theta) % (2 * math.pi)
    if t > math.pi:
        t -= 2 * math.pi
    pre, post = [], []
    if t < 0:
        pre, post, t = pre + [("x", 0)], [("x", 0)] + post, -t
    if t > math.pi / 2:
        pre = pre + [("z", 0), ("z", 1), ("x", 0)]
        post = [("x", 0)] + post
        t = math.pi - t
    return t, pre, post


def _emit_folded_rzz(qc, lam, qa, qb):
    tc, pre, post = fold_rzz(lam)
    qmap = {0: qa, 1: qb}
    for g, q in pre:
        getattr(qc, g)(qmap[q])
    qc.rzz(tc, qa, qb)
    for g, q in post:
        getattr(qc, g)(qmap[q])


def dciqp_reference_marginal(params_list, gates, n_feat, observables, q2g,
                             M: int, seed: int = 424242) -> np.ndarray:
    """Van den Nest reference for what dcIQP produces on the data register:
    the PADDED uniform mixture of component marginals (identical to the
    cIQP data marginal). Used by the audit."""
    padded, _ = _pad_to_power_of_2(params_list)
    active = precompute_active_lists(observables, gates, q2g)
    rng = np.random.default_rng(seed)
    z = np.zeros(len(observables))
    for theta in padded:
        lat = sample_latents(n_feat, M, rng, antithetic=True)
        zl, _ = forward_batch(theta, ParityCache(lat, gates), active)
        z += zl / len(padded)
    return z


# ═════════════════════════════════════════════════════════════════════════
# §2  cat-cIQP compiler + exact dense verifier
# ═════════════════════════════════════════════════════════════════════════

def build_cat_ciqp(params_list: list[np.ndarray],
                   base_gates: list[tuple[int, ...]],
                   n_feat: int,
                   m_copies: int,
                   walsh_support: list[int] | None = None):
    """Compile MoIQP → coherent diagonal on n_feat + a·m_copies qubits with
    GHZ ancilla buses. Ancilla k occupies qubits
        n_feat + k·m_copies + r,   r = 0..m_copies-1  (copies).
    Each compiled gate (j, S) uses copy r_j = j mod m_copies of every
    ancilla in S (round-robin de-congestion; a placement-aware assignment
    would pick the physically nearest copy — same algebra).
    If walsh_support is given, only those S (as bitmask ints) are emitted —
    the deployment object of a Walsh-sparse-trained model.
    Returns (gates, params, info). Prep spec: H+CX-tree (depth ⌈log2 m⌉) or
    constant-depth dynamic GHZ (Bäumer et al.) per ancilla bus; the audit
    simulates the prepared cats directly."""
    padded, a = _pad_to_power_of_2(params_list)
    L_pad = 1 << a
    G = len(base_gates)
    per_gate = np.stack(padded, axis=1)                    # (G, L_pad)
    tilde = np.zeros_like(per_gate)
    for j in range(G):
        tilde[j] = _walsh_hadamard(per_gate[j]) / L_pad

    support = list(range(L_pad)) if walsh_support is None else list(walsh_support)

    def copy_qubit(k: int, r: int) -> int:
        return n_feat + k * m_copies + r

    out_gates: list[tuple[int, ...]] = []
    out_params: list[float] = []
    for j, base in enumerate(base_gates):
        r = j % m_copies
        for S_int in support:
            ang = float(tilde[j, S_int])
            if abs(ang) < 1e-15:
                continue
            anc = tuple(copy_qubit(k, r) for k in range(a) if (S_int >> k) & 1)
            out_gates.append(tuple(sorted(tuple(base) + anc)))
            out_params.append(ang)

    weights = [len(g) for g in out_gates]
    layers = greedy_gate_layers(out_gates)
    info = {
        "n_feat": n_feat, "a": a, "m_copies": m_copies,
        "n_total": n_feat + a * m_copies,
        "n_deploy_gates": len(out_gates),
        "max_weight": max(weights) if weights else 0,
        "sched_layers": len(layers),
        "ghz_prep": {"unitary_depth": int(np.ceil(np.log2(max(m_copies, 1)))),
                     "dynamic_depth": "O(1) w/ feedforward (PRX Quantum 5, 030339)",
                     "cx_per_bus_unitary": m_copies - 1},
    }
    return out_gates, np.asarray(out_params), info


def exact_cat_ciqp_data_marginal(params_list, base_gates, n_feat,
                                 m_copies: int) -> np.ndarray:
    """Dense-statevector data-register distribution of the cat-cIQP circuit
    (small n only; audit tool). Initial state: |+⟩^{n_feat} ⊗ (⊗_k cat_k);
    apply the compiled diagonal; H on data; return marginal over ancillas.
    Convention: qubit q ↔ bit (z >> q) & 1."""
    padded, a = _pad_to_power_of_2(params_list)
    gates_c, params_c, _ = build_cat_ciqp(params_list, base_gates, n_feat,
                                          m_copies)
    N = n_feat + a * m_copies
    dim = 1 << N
    idx = np.arange(dim, dtype=np.uint64)
    bits = ((idx[:, None] >> np.arange(N, dtype=np.uint64)[None, :]) & 1
            ).astype(np.int8)

    # amplitude: data uniform; ancilla bus k must be all-0 or all-1
    amp = np.full(dim, 1.0 / np.sqrt(1 << n_feat), dtype=np.complex128)
    for k in range(a):
        cols = bits[:, n_feat + k * m_copies: n_feat + (k + 1) * m_copies]
        cat_ok = (cols.sum(axis=1) % m_copies == 0) if m_copies > 1 else \
                 np.ones(dim, bool)
        # all-equal test (all zeros or all ones):
        cat_ok = np.all(cols == cols[:, :1], axis=1)
        amp *= np.where(cat_ok, 1.0 / np.sqrt(2.0), 0.0)

    # diagonal phases
    phase = np.zeros(dim)
    for g, th in zip(gates_c, params_c):
        par = bits[:, list(g)].sum(axis=1) % 2
        phase += th * (1.0 - 2.0 * par)
    amp = amp * np.exp(1j * phase)

    # H^{⊗n_feat} on data: ψ'(x, anc) = 2^{-n/2} Σ_z (-1)^{x·z} ψ(z, anc)
    psi = amp.reshape([2] * N, order="F")   # axis q = qubit q
    for q in range(n_feat):
        psi_m = np.moveaxis(psi, q, 0)
        a0, a1 = psi_m[0].copy(), psi_m[1].copy()
        psi_m[0] = (a0 + a1) / np.sqrt(2.0)
        psi_m[1] = (a0 - a1) / np.sqrt(2.0)
        psi = np.moveaxis(psi_m, 0, q)
    prob = np.abs(psi.reshape(dim, order="F")) ** 2
    # marginalize ancillas: sum over ancilla bits
    prob = prob.reshape((1 << n_feat, 1 << (a * m_copies)), order="F").sum(axis=1)
    return prob


def exact_single_iqp_distribution(theta, gates, n: int) -> np.ndarray:
    """Exact p_θ(x) = |(WHT[e^{iφ}])[x]|²/4^n via complex fast WHT (audit)."""
    dim = 1 << n
    idx = np.arange(dim, dtype=np.uint64)
    bits = ((idx[:, None] >> np.arange(n, dtype=np.uint64)[None, :]) & 1
            ).astype(np.int8)
    phase = np.zeros(dim)
    for g, th in zip(gates, theta):
        par = bits[:, list(g)].sum(axis=1) % 2
        phase += th * (1.0 - 2.0 * par)
    v = np.exp(1j * phase)
    h = 1
    while h < dim:
        for i in range(0, dim, 2 * h):
            x, y = v[i:i + h].copy(), v[i + h:i + 2 * h].copy()
            v[i:i + h] = x + y
            v[i + h:i + 2 * h] = x - y
        h *= 2
    return np.abs(v / dim) ** 2


# ═════════════════════════════════════════════════════════════════════════
# §3  Walsh-sparse MoIQP trainer
# ═════════════════════════════════════════════════════════════════════════

def walsh_synthesize(phi: np.ndarray, support: list[int], a: int) -> list[np.ndarray]:
    """θ^{(ℓ)}_j = Σ_{S∈support} (−1)^{ℓ·S} φ_{j,S}.  phi: (|G|, |support|)."""
    L = 1 << a
    thetas = []
    for ell in range(L):
        signs = np.array([1.0 - 2.0 * (bin(ell & S).count("1") % 2)
                          for S in support])
        thetas.append(phi @ signs)
    return thetas


def train_moiqp_walsh_sparse(
    binary: np.ndarray, raw: np.ndarray,
    gates, q2g, D: int, B: int, a: int,
    observables,
    walsh_support: list[int],
    n_epochs: int = 300, mc_batch: int = 2048, lr: float = 0.02,
    eta_psck: float = 5.0, heat_scale: float = 1.0,
    psck_taus=(0.1, 0.3, 0.5, 0.7, 0.9),
    seed: int = 42, grad_clip: float = 10.0, unbiased: bool = True,
    verbose: bool = True,
):
    """PSCK training with the mixture parameterized DIRECTLY in the Walsh
    domain on a restricted support U (∅ must be included). Deployment gate
    count of the coherent cat-cIQP becomes |U|·|G| by construction. Forward
    cost per epoch equals a standard L = 2^a MoIQP epoch; the only addition
    is the Walsh synthesis/analysis chain rule
        dL/dφ_{j,S} = Σ_ℓ (−1)^{ℓ·S} dL/dθ^{(ℓ)}_j .
    Returns (best_phi (|G|,|U|), support, hist)."""
    assert 0 in walsh_support, "support must contain S=∅ (mixture mean)"
    n = D * B
    L = 1 << a
    z_data = z_data_batch(binary, observables)
    iu = np.triu_indices(D, k=1)
    rho_target = np.corrcoef(raw.T)[iu]
    active = precompute_active_lists(observables, gates, q2g)
    omega, Jstar, _, _, _ = build_psck_kernel(
        z_data, observables, D, B, eta=eta_psck, taus=psck_taus,
        heat_scale=heat_scale)

    ng = len(gates)
    U = list(walsh_support)
    rng = np.random.default_rng(seed)
    phi = rng.normal(0, 0.1 / max(1, len(U)) ** 0.5, (ng, len(U)))
    signs_mat = np.array([[1.0 - 2.0 * (bin(ell & S).count("1") % 2)
                           for S in U] for ell in range(L)])   # (L, |U|)
    m_adam = np.zeros_like(phi); v_adam = np.zeros_like(phi)
    rng_mc = np.random.default_rng(seed + 99991)
    best = (np.inf, phi.copy())
    hist = {"loss": [], "z_err": [], "rho_err": []}

    for ep in range(n_epochs):
        thetas = [phi @ signs_mat[ell] for ell in range(L)]
        caches, args_l, zs = [], [], []
        for ell in range(L):
            lat = sample_latents(n, mc_batch, rng_mc, antithetic=True)
            c = ParityCache(lat, gates)
            zl, al = forward_batch(thetas[ell], c, active)
            caches.append(c); args_l.append(al); zs.append(zl)
        z_mix = np.mean(zs, axis=0)

        if unbiased:
            zsB = []
            for ell in range(L):
                lat = sample_latents(n, mc_batch, rng_mc, antithetic=True)
                zl, _ = forward_batch(thetas[ell], ParityCache(lat, gates),
                                      active)
                zsB.append(zl)
            z_mix_B = np.mean(zsB, axis=0)
            loss = psck_mmd2_unbiased(z_mix, z_mix_B, z_data, omega, Jstar,
                                      eta_psck)
            dL_dz = psck_mmd2_unbiased_grad_wrt_za(
                z_mix, z_mix_B, z_data, omega, Jstar, eta_psck)
        else:
            loss, dL_dz = psck_mmd2_and_grad(z_mix, z_data, omega, Jstar,
                                             eta_psck)

        dL_dz_l = dL_dz / L
        g_phi = np.zeros_like(phi)
        for ell in range(L):
            g_theta = backward_batch(thetas[ell], caches[ell], active,
                                     args_l[ell], dL_dz_l)     # (ng,)
            g_phi += np.outer(g_theta, signs_mat[ell])          # chain rule
        gn = float(np.linalg.norm(g_phi))
        if gn > grad_clip:
            g_phi *= grad_clip / gn

        t = ep + 1
        m_adam = 0.9 * m_adam + 0.1 * g_phi
        v_adam = 0.999 * v_adam + 0.001 * g_phi ** 2
        phi -= lr * (m_adam / (1 - 0.9 ** t)) / (
            np.sqrt(v_adam / (1 - 0.999 ** t)) + 1e-8)

        z_err = float(np.mean(np.abs(z_mix - z_data)))
        rho_m, _ = pearson_value_and_jacobian(z_mix, observables, D, B)
        rho_err = float(np.mean(np.abs(rho_m[iu] - rho_target)))
        hist["loss"].append(float(loss)); hist["z_err"].append(z_err)
        hist["rho_err"].append(rho_err)
        if loss < best[0]:
            best = (float(loss), phi.copy())
        if verbose and (ep % 50 == 0 or ep == n_epochs - 1):
            print(f"    [walsh k={len(U)}] ep {ep:4d}  L={loss:.4e}  "
                  f"|Δz|={z_err:.4f}  |Δρ|={rho_err:.4f}")
    return best[1], U, hist


def walsh_sparse_to_components(phi: np.ndarray, support: list[int],
                               a: int) -> list[np.ndarray]:
    """Expand trained Walsh-sparse parameters to L = 2^a component angle
    vectors (for mixture/dcIQP deployment or standard evaluation)."""
    return walsh_synthesize(phi, support, a)
